spring:
  config:
    activate:
      on-profile: integration
  datasource:
    hikari:
      auto-commit: false

no.nav.security.jwt.issuer:
  selvbetjening:
    discoveryurl: http://metadata-selvbetjening
    accepted_audience: aud-localhost
    cookiename: localhost-idtoken
  tokenx:
    discoveryurl: http://metadata-selvbetjening
    accepted_audience: aud-localhost

mock:
  enabled: true
  port: 10093

api:
  client:
    yrkesskade-mottak-url: http://localhost:9080
    enhetsregister:
      url: http://localhost:${mock.port}/enhetsregisteret/api
    altinn:
      url: http://localhost:${mock.port}/altinn/
      apiKey: test

maskinporten:
  clientId: foo
  scopes: bar
  wellKnownUrl: nav.no
  clientJwk: yas