spring:
  application.name: yrkesskade-melding-api
  datasource:
    url: jdbc:postgresql://localhost:5432/yrkesskade_melding

no.nav.security.jwt.issuer.selvbetjening:
  discoveryurl: http://metadata-selvbetjening
  accepted_audience: aud-localhost
  cookiename: localhost-idtoken

mock:
  enabled: true
  port: 10091

api:
  client:
    yrkesskade-mottak-url: http://localhost:9080
    enhetsregister:
      url: http://localhost:${mock.port}/enhetsregisteret/api/enheter
    altinn:
      fallbackUrl: http://localhost:${mock.port}/altinn/
      apiKey: test
      proxyUrl: http://localhost:${mock.port}/altinn/