spring:
  config:
    activate:
      on-profile: integration
  datasource:
    hikari:
      auto-commit: false

no.nav.security.jwt.issuer:
  tokenx:
    discoveryurl: http://metadata-selvbetjening
    accepted_audience: aud-localhost

mock:
  enabled: true
  port: 10093

api:
  client:
    yrkesskade-mottak-url: http://localhost:9080
    enhetsregister:
      url: http://localhost:${mock.port}/enhetsregisteret/api/enheter
    altinn:
      fallbackUrl: http://localhost:${mock.port}/altinn/
      apiKey: test
      proxyUrl: http://localhost:${mock.port}/altinn/

maskinporten:
  client:
    enabled: false
  clientId: foo
  scopes: bar
  wellKnownUrl: nav.no
  clientJwk: yas