spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yrkesskade_melding

no.nav.security.jwt.issuer:
  selvbetjening:
    discoveryurl: https://fakedings.dev-gcp.nais.io/fake/.well-known/openid-configuration
    accepted_audience: aud-localhost
    cookiename: selvbetjening-idtoken
  tokenx:
    discoveryurl: https://fakedings.dev-gcp.nais.io/fake/.well-known/openid-configuration
    accepted_audience: dev-gcp:yrkesskade:yrkesskade-melding-api

mock:
  enabled: true
  port: 10091

api:
  client:
    yrkesskade-mottak-url: http://localhost:9080
    enhetsregister:
      url: http://localhost:${mock.port}/enhetsregisteret/api/enheter
    altinn:
      fallbackUrl: http://localhost:${mock.port}/altinn/
      apiKey: test
      proxyUrl: http://localhost:${mock.port}/altinn/