KAFKA_BROKERS: http://localhost:9092
KAFKA_SCHEMA_REGISTRY: http://localhost:8081
NAIS_CLUSTER_NAME: lokal

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/yrkesskade_melding
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username="igroup" password="itest";
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
    consumer:
      group-id: srvc01
    producer:
      client-id: srvp01

# bruk oneshot for å opprette topic
kafka:
  topic:
    skademelding-innsendt: privat-yrkesskade-skademeldinginnsendt

funksjonsbrytere:
  enabled: false

no.nav.security.jwt.issuer:
  tokenx:
    discoveryurl: https://fakedings.dev-gcp.nais.io/fake/.well-known/openid-configuration
    accepted_audience: dev-gcp:yrkesskade:yrkesskade-melding-api

maskinporten.client.enabled: false

mock:
  enabled: true
  port: 10091
  enhetsregister:
    port: 10094

api:
  client:
    yrkesskade-mottak-url: http://localhost:9080
    enhetsregister:
      url: http://localhost:${mock.enhetsregister.port}/enhetsregisteret/api
    altinn:
      url: http://localhost:${mock.port}/altinn/
      apiKey: test