spring:
  config:
    activate:
      on-profile: integration

no.nav.security.jwt.issuer.selvbetjening:
  discoveryurl: http://metadata-selvbetjening
  accepted_audience: aud-localhost
  cookiename: localhost-idtoken

mock:
  enabled: true
  port: 9092

api:
  client:
    yrkesskade-mottak-url: http://localhost:9080
    enhetsregister:
      url: http://localhost:${mock.port}/enhetsregisteret/api/enheter
    altinn:
      fallbackUrl: http://localhost:${mock.port}/altinn/
      apiKey: test
      gatewayApiKey: test
      proxyUrl: http://localhost:${mock.port}/altinn/