api:
  client:
    yrkesskade-mottak-url: https://yrkesskade-melding-mottak.dev.intern.nav.no
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal
  metrics.export.prometheus.enabled: true
