spring:
  config:
    activate:
      on-profile: integration
  datasource:
    hikari:
      auto-commit: false
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    consumer:
      auto-offset-reset: earliest
      group-id: yrkesskade

funksjonsbrytere:
  enabled: false
NAIS_CLUSTER_NAME: lokal

kafka:
  topic:
    skademelding-innsendt: test

no.nav.security.jwt.issuer:
  tokenx:
    discoveryurl: http://metadata-selvbetjening
    accepted_audience: aud-localhost

mock:
  enabled: true
  port: 10093

api:
  client:
    yrkesskade-mottak-url: http://localhost:9080
    enhetsregister:
      url: http://localhost:${mock.port}/enhetsregisteret/api
    altinn:
      url: http://localhost:${mock.port}/altinn/
      apiKey: test

maskinporten:
  client:
    enabled: false
  clientId: foo
  scopes: bar
  wellKnownUrl: nav.no
  clientJwk: yas