spring:
  application.name: yrkesskade-melding-api
  datasource:
    url: jdbc:postgresql://${YRKESSKADE_API_DB_HOST}:${YRKESSKADE_API_DB_PORT}/${YRKESSKADE_API_DB_DATABASE}
    username: ${YRKESSKADE_API_DB_USERNAME}
    password: ${YRKESSKADE_API_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
      data-source-properties.stringtype: unspecified # Nødvendig for å kunde sende en String til et json-felt i PostgresSql
  flyway:
    enabled: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        ddl-auto: none

no.nav.security.jwt.issuer:
  tokenx:
    discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
    accepted_audience: dev-gcp:yrkesskade:yrkesskade-melding-api

maskinporten.client.enabled: true

api:
  client:
    yrkesskade-mottak-url: https://yrkesskade-melding-mottak.dev.intern.nav.no
    enhetsregister:
      url: https://data.brreg.no/enhetsregisteret/api/enheter
    altinn:
      fallbackUrl: https://api-gw-q1.adeo.no # TEST (ta bort -q1 for prod)
      apiKey: ${ALTINN_HEADER}
      proxyUrl: https://arbeidsgiver.dev.intern.nav.no/altinn-rettigheter-proxy #TEST (ta bort dev for prod)
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal
      path-mapping.prometheus: prometheus
  metrics:
    export.prometheus.enabled: true
    tags:
      application: ${spring.application.name}
